apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-virtualkubelet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes-virtualkubelet
  template:
    metadata:
      labels:
        app: hello-kubernetes-virtualkubelet
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5  
        resources:
          limits:
            memory: "0.5G"
            cpu: "0.5"
          requests:
            memory: "0.5G"
            cpu: "0.5"
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
      nodeSelector:
        kubernetes.io/hostname: virtual-kubelet-aci-linux
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet/aci
        value: linux
        effect: NoSchedule