# Settings for the Facial Image Recognizer
imageRecognizer:
  replicaCount:
    pods: 1
    aci: 0
  image:
    repository: rbitia/fr-ir
    tag: latest
    pullPolicy: Always
  resources:
    limits:
     cpu: 500m
     memory: 1.5G
    requests:
     cpu: 500m
     memory: 1.5G
  azureBlob:
     storageAccount: acidemopictures
  virtualKubelet:
    nodeName:

# Settings for the Facial Image Recognizer UI
frontend:
  replicaCount: 1
  image:
    repository: rbitia/fr-frontend
    tag: latest
    pullPolicy: Always
  service:
    name: frontend
    type: ClusterIP
    externalPort: 8080
    internalPort: 8080
  ingress:
    enabled: true
    hosts: []
    annotations:
      kubernetes.io/ingress.class: nginx
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Settings for Facial Image Recognizer Backend
backend:
  replicaCount: 1
  image:
    repository: rbitia/aci-webserver
    tag: latest
    pullPolicy: Always
  service:
    name: backend
    type: ClusterIP
    externalPort: 80
    internalPort: 8000
  ingress:
    enabled: true
    hosts: []
    annotations:
      kubernetes.io/ingress.class: nginx
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
